### ISSUE TITLE
Supporting BBCode in Preview

### ISSUE THREAD

**Issue by Leinad4Mind** [ForumHulp/pageaddon#7]
It would be great to have a Preview mode for bbcode, so we can see the result before submitting. Cheers

**Comment by ForumHulp** [comment]
With this addon you don't need bbcode anymore but for older pages a standard bbcode preview is build in the 3.1.3 version

**Comment by Galixte** [comment]
@Leinad4Mind did you ask to EXTENSIONS team to add the preview feature on editor page from Extension Pages?

**Comment by ForumHulp** [comment]
No, the preview is in the addon. It can only show standard bbcode

**Comment by Galixte** [comment]
So, you can fix this to display additional BBCode like these from ABBC3 extension, many extension can show these in ACP, why not your extension? ;)

**Comment by ForumHulp** [comment]
Because the addon is only a editor so you don't need bbcode anymore Raphaël.
You should ask your question to he phpbb team.

**Comment by Leinad4Mind** [comment]
What he said is that he have enabled the basic (original) BBCodes from phpbb installation. All customs bbcodes will not be processed in the addon. For people with phpbb BBCodes only its great to have bbcode support on this.

Anyway for people that are 0 at html and want to use customs bbcodes then this ext is not for them. We need to ask to pages extension itself for adding a preview in ACP. (ofc we can preview on forum and copy paste to ACP... But it would be way easier to have a preview on acp.

**Comment by Galixte** [comment]
Ok I’ll ask to Extensions team if they can add the preview feature on editor page.
